### ISSUE TITLE
Intro Video does not play on iOS & is not cropped properly on mobile

### ISSUE THREAD

**Issue by ChaseHall** [XLabsProject/XLabsProject.github.io#10]
[The video is cropped on mobile](https://i.imgur.com/zSWo502.png), should fix. ;p

**Comment by Niaz-Ul-Haque** [comment]
I would love to deal with this, please assign me this one.

**Comment by ChaseHall** [comment]
Go for it!

**Comment by ChaseHall** [comment]
@Niaz-Ul-Haque I've also noticed, the video doesn't actually show on mobile. Would you happen to know why/be able to help?

**Comment by Niaz-Ul-Haque** [comment]
I'll do the fixing during the coming weekends, but if I am to guess, shouldn't be something major, just some stylings mixing up. That's just my guess for now (by looking at the issue and the img). Will give more information on why it happened after I get to fix it. 

Thank you for assigning me this, will be good practice for me!

**Comment by ChaseHall** [comment]
Works for us! We really appreciate you helping us out.

**Comment by thePeterG** [comment]
The video needs to be moved to the xlabs YouTube channel when a custom video is made to avoid GitHub usage limits.

**Comment by Niaz-Ul-Haque** [comment]
Ahh srry its taking a while but don't worry. ill be working on it tommrw or the day after. got my finals next week and the next next week. So focusing all at once. srry for the delay but don't worry. Thank you!
