### ISSUE TITLE
Update IW6x FAQ

### ISSUE THREAD

**Issue by EST3V4M** [XLabsProject/XLabsProject.github.io#14]
![image](https://user-images.githubusercontent.com/55590586/99791198-33522700-2b1d-11eb-8ea0-7347c9399e67.PNG)

Update info - "**level 70**" > "**level 60**"
Fix typo - "**/unlockallto**" > "**/unlockall to**"

**Comment by ChaseHall** [comment]
Thanks! I was a bit rushed making that page and so I forgot to check. Really appreciate it.
