### ISSUE TITLE
Fix drop-down menu

### ISSUE THREAD

**Issue by EST3V4M** [XLabsProject/XLabsProject.github.io#16]
If one of the drop-down menus is clicked, it will remain active until it is clicked again, causing this (image)

![image](https://user-images.githubusercontent.com/55590586/99904483-03448880-2cc3-11eb-8dd9-b6560e7a8f6b.png)

**Comment by ChaseHall** [comment]
[Made some progress on this](https://i.imgur.com/zKIiaJP.gif), got the other menu to close if you click on the other menu, however hover is still buggy.
