### ISSUE TITLE
IW4x Support page

### ISSUE THREAD

**Issue by thePeterG** [XLabsProject/XLabsProject.github.io#2]
Create and add the client/server install info from iw4x.org guides to support_iw4x.html.

**Comment by ChaseHall** [comment]
Think I got this sorted, see the [site](https://xlabs.dev/test_design/support_iw4x.html) or [source](https://github.com/XLabsProject/XLabsProject.github.io/blob/master/test_design/support_iw4x.html). You can always re-open this if you want more added and I can get on it.

**Comment by thePeterG** [comment]
Looks good.
