### ISSUE TITLE
Working console commands for IW4x, IW6x, and S1x

### ISSUE THREAD

**Issue by thePeterG** [XLabsProject/XLabsProject.github.io#22]
Please add to the list of working console commands for https://xlabs.dev/console_commands.html

Include: command, compatible client, usage example, description

**Comment by ChxseH** [comment]
Think we cover most/all the important commands now, closing for now. Please re-open if you think we could add more.

**Comment by ChxseH** [comment]
spawnBot, `reconnect` `disconnect` `quit` `listassetpool` `dvarDump` `commandDump` `demiGod`

**Comment by ChxseH** [comment]
WIP XInput dvars [here](https://github.com/XLabsProject/iw4x-client/pull/75/commits/9f6b5c62143c1e3186de707d8192b12596785f06#diff-cf77e77b8d22b380e63af4deaf29e53c7b897ffbd1bc30f32f44af0a9792d177R447-R452)
