### ISSUE TITLE
Replace Intro Video

### ISSUE THREAD

**Issue by ChaseHall** [XLabsProject/XLabsProject.github.io#23]
Replace intro video with panorama [here](https://slykuiper.com/vrview-master/index.html?image=//slykuiper.com/assets/images/work/360/iw6x_Panorama.jpg&is_stereo=false)

Provided it works on mobile, this will replace #10.

---

"make it display that or render it as an animation, idk
or just put an iframe idc :joy:
you can just embed vrview from here: https://github.com/googlearchive/vrview
pretty sure we can also do some small animation using webgl
i mean you only need to project the texture onto a sphere"

**Comment by thePeterG** [comment]
Only VIPs will be able to see the context links do might want to specify the goal here.

**Comment by ChaseHall** [comment]
Yup, of course, I made the issue on mobile just to remind myself

**Comment by thePeterG** [comment]
Think 🐍 was going to take a stab at it

**Comment by momo5502** [comment]
done
