### ISSUE TITLE
Floating Menu Blocking Section Link Content

### ISSUE THREAD

**Issue by thePeterG** [XLabsProject/XLabsProject.github.io#27]
The floating navigation menu is blocking content when using section links. See https://xlabs.dev/iw4x_faq.html

**Comment by ChaseHall** [comment]
For reference since I am blind sometimes, [this is what happens](https://i.imgur.com/lVsYLhM.gif)

**Comment by ChaseHall** [comment]
[Fixed](https://i.imgur.com/cHQGdas.gif)
