### ISSUE TITLE
Footer Icons do not show on mobile (Android?)

### ISSUE THREAD

**Issue by thePeterG** [XLabsProject/XLabsProject.github.io#3]
Footer Icons don't show on mobile.

**Comment by ChaseHall** [comment]
[Footer Icons as in the twitter/discord/etc buttons? They show for me](https://i.imgur.com/IDzgESh.png)

**Comment by thePeterG** [comment]
Might be OS/ browser specific. I'll do some testing.

**Comment by ChaseHall** [comment]
Closing this as I can get it to render on my friends android device. Re-open if you encounter issues:)
