### ISSUE TITLE
Implement PeterG's ToC across the rest of the site

### ISSUE THREAD

**Issue by ChxseH** [XLabsProject/XLabsProject.github.io#5]
Implement PeterG's [current solution](https://xlabs.dev/iw4x_faq) for a ToC across:  
* Client Support(s)
* FAQs
* Error Page(s)

**Comment by ChaseHall** [comment]
Just finalized splitting up client & server, will rename this to just focus on TOC on each page.

**Comment by thePeterG** [comment]
Working on this but trying to make it pretty.
