### ISSUE TITLE
Navbar Improvements (Sticky)

### ISSUE THREAD

**Issue by ChaseHall** [XLabsProject/XLabsProject.github.io#9]
Good job peter on the new menu, looks good. However I noticed a couple things we discussed, just making an issue for reference.
~~I personally believe the nav menu should be hover, instead of forcing the user to click on the drop down, as that isn't as clear.~~

~~This will prevent the issue of [menus overlapping](https://cdn.discordapp.com/attachments/777700976751935508/778655098619953152/unknown.png)~~

We can/should also make it stick to the top of the screen when you scroll, just a thought.

**Comment by momo5502** [comment]
I like the hover idea. Also make the corners of the logo rounded pls

**Comment by thePeterG** [comment]
Yes to all.

**Comment by thePeterG** [comment]
Also need to fix the menu button color for mobile.

**Comment by ChaseHall** [comment]
> Also need to fix the menu button color for mobile.

This looks right to me, however I might be blind, [here's what it was previously](https://i.imgur.com/RKNFHVM.png) and [here
s what changing it to 1.5px instead of 1 does](https://i.imgur.com/OSb8fyf.png)

**Comment by thePeterG** [comment]
I just meant changing it to a white color to contrast better with the background.

**Comment by ChaseHall** [comment]
> I just meant changing it to a white color to contrast better with the background.

Derp. [How's this?](https://i.imgur.com/mFLZfvb.png)

**Comment by thePeterG** [comment]
Yeah, looks good. I I notice bootstrap 4 has removed drop-down on hover so I'll have to look for a solution that doesn't add a bunch of scripts

**Comment by albedoa** [comment]
You add this rule:

```
.nav-item:hover .dropdown-menu {
  display: block;
}
```

You will need to remove an existing margin because it is creating a gap between the `li.nav-item` and its child `div.dropdown-menu` that interrupts the hover state when moving from one to the other:

```
.nav-item {
  margin-bottom: 0;
}

**Comment by thePeterG** [comment]
Worked! Thanks for the help
