### ISSUE TITLE
Update repair guide on verifying file integrity

### ISSUE THREAD

**Issue by WantedDV** [XLabsProject/XLabsProject.github.io#94]
### Problem
It is not uncommon for users to place modded content in their game directory. When it comes to resolving issues it is important that the state of the users files:
 1. maintains proper folder structure, and 
 2. does not contain miscellaneous (potentially invasive) files such as dll or exe.

The repair guide currently does not check for extra files, giving users and support members the false impression that the game is clean. 

### Solution
This most basic solution to this would be to include a `filelist.txt` listing all game files on the website. Here are the file list for the clean installs. Users should have their files in this state before installing mods by XLabs. Files are sorted naturally to match windows explorer.

[iw4x-files.txt](https://github.com/XLabsProject/XLabsProject.github.io/files/10879728/iw4x-files.txt)
[iw6x-files.txt](https://github.com/XLabsProject/XLabsProject.github.io/files/10879729/iw6x-files.txt)
[s1x-files.txt](https://github.com/XLabsProject/XLabsProject.github.io/files/10879726/s1x-files.txt)

**Comment by Dss0** [comment]
what diamante said, this also just adds an extra (complicated) step to the process. People are already struggling with it as it is.
